#
ec_board_ctrl :
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 300000000
  sync_point_ns : 500000
  power_off_boards: false
  reset_micro : true
  
ec_boards_base :
  app_mode : run_mode
  #app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  #fault_power_off : true
  use_ecat_pos_as_id : false

zmq_pub :
  base_port : 9000
  uri : "tcp://*:"
  fd_timeout_us : 100000

zmq_rep :
  uri: "tcp://*:5555"
  zmq_rcvtimeo_ms : 500
  #pipe_prefix : "/tmp/nrt_pipes/"

ati_config :
  ati_ip_addr : 192.168.1.1
  ft_ecat_pos : 1
  save_calib_matrix : false
  #calib_mat_file : ../examples/ati_ft6_calib/data/ones.txt
  calib_mat_file : ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_right_Foot_ft_147_sens8.txt
  dump_log : true


#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]
    
CentAcESC_X: &CentAcESC_X
  sign: 1
  pos_offset: 0
  enable_sandbox: false
  enable_pos_filter: false
  #control_mode : 00_idle_ctrl
  control_mode : 3B_motor_pos_ctrl
  #control_mode : D4_impedance_ctrl
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    #impedance:  [0.0, 0.0, 5.0, 0.001, 0.08]
    impedance:   [250.0, 5.0, 2.0, 0.001, 0.08]
  aux_pdo : # names defined in SDO index 0x8002 
     _rd :  [ pos_ref_fb ]
     _rd :  [ pos_ref_fb, motor_enc_warn, motor_enc_err, link_enc_warn, link_enc_err ]
     _rd :  [ iq_ref_fb, id_ref_fb ]
     _wr :  [ iq_ref ]
     _wrd : [ "iq_offset&&iq_out_fb" ]
     _wrd : [ "ts&&rtt" ]

Ft6Msp432ESC_X:
  analog_sample_freq_HZ: 20000

AinMsp432ESC_X:
  analog_sample_freq_HZ: 1000

#############################
# Head
#############################
LpESC_105:
  sign: 1
  pos_offset: 0



#############################
# Right tibia
#############################
CentAcESC_41:
  sign: 1
  pos_offset: 0


CentAcESC_42:
  sign: -1
  pos_offset: 0

    
CentAcESC_43:
  sign: -1
  pos_offset: 0

CentAcESC_44:
  sign: -1
  pos_offset: 0

CentAcESC_45:
  sign: 1
  pos_offset: 0

CentAcESC_46:
  sign: -1
  pos_offset: 0


#############################
# Left tibia
#############################
CentAcESC_51:
  sign: 1
  pos_offset: 0

CentAcESC_52:
  sign: 1
  pos_offset: 0

CentAcESC_53:
  sign: -1
  pos_offset: 0

CentAcESC_54:
  sign: 1
  pos_offset: 0
 
CentAcESC_55:
  sign: 1
  pos_offset: 0

CentAcESC_56:
  sign: -1
  pos_offset: 0

##############################
# RIGHT ARM
##############################

CentAcESC_11:
  sign: -1
  pos_offset: -45

CentAcESC_12:
  sign: -1
  pos_offset: -45

CentAcESC_13:
  sign: -1
  pos_offset: 0

CentAcESC_14:
  sign: -1
  pos_offset: 0

CentAcESC_15:
  sign: -1
  pos_offset: 0

CentAcESC_16:
  sign: -1
  pos_offset: 0

CentAcESC_17:
  sign: -1
  pos_offset: 0
  
# RA_HA = 19
LpESC_19:
  sign: 1
  pos_offset: 0

##############################
# LEFT ARM
##############################
    
CentAcESC_21:
  sign: 1
  pos_offset: -45

CentAcESC_22:
  sign: -1
  pos_offset: 45

CentAcESC_23:
  sign: -1
  pos_offset: 0

CentAcESC_24:
  sign: 1
  pos_offset: 0

CentAcESC_25:
  sign: -1
  pos_offset: 0

CentAcESC_26:
  sign: 1
  pos_offset: 0

CentAcESC_27:
  sign: -1
  pos_offset: 0

# LA_HA = 29
LpESC_29:
  sign: 1
  pos_offset: 0
 
#############################
# WAIST
#############################

CentAcESC_31:
  sign: 1
  pos_offset: 0

CentAcESC_32:
  sign: 1
  pos_offset: 0
